### ISSUE TITLE
[Enhancement] Power off Vario if the battery level is too low.

### ISSUE THREAD

**Issue by olekuz** [har-in-air/ESP32C3_BLUETOOTH_AUDIO_VARIO#1]
It would be nice to showdown Vario when the battery level is critically low to prevent over-discharge and save the battery from degradation.

**Comment by har-in-air** [comment]
Commercial Lipoly batteries  already have protection  modules for overcharge and overdischarge and max current. It's the thin rectangular  pcb connected to the raw battery tabs. You shouldn't  be using a raw lipoly or liion battery without the protection  module. You can find replacement  boards easily on aliexpress  etc. They are specified by the voltage 1S, 2S etc and the max  current.

Sent from Yahoo Mail on Android 
 
  On Fri, 21 Oct 2022 at 14:27, Oleksandr ***@***.***> wrote:   


It would be nice to showdown Vario when the battery level is critically low to prevent over-discharge and save the battery from degradation.
